title: Andrea Herrera BÃ³rquez
logo: /assets/img/LSE Geography Headshots 2023-211.jpg
description: PhD candidate, Economic Geography, LSE
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
