title: Andrea Herrera BÃ³rquez
logo: /assets/img/LSE Geography Headshots 2023-211.jpg
description: PhD Candidate in Economic Geography at LSE.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
